name: Tests
on:
  push:
  pull_request:

jobs:
  test:
    name: ${{ matrix.redmine }} ruby-${{ matrix.ruby }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby: ['2.7', '3.0', '3.1', '3.2']
        redmine: ['4.2-stable', '5.0-stable', '5.1-stable']
        exclude:        
          - ruby: '3.0'
            redmine: 4.2-stable            
          - ruby: '3.1'
            redmine: 4.2-stable            
          - ruby: '3.2'
            redmine: 4.2-stable
          - ruby: '3.2'
            redmine: 5.0-stable
      fail-fast: false

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: redmine_test
        ports:
          # will assign a random free host port
          - 3306/tcp
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Verify MySQL connection from host
        run: |
          mysql --host 127.0.0.1 --port ${{ job.services.mysql.ports[3306] }} -uroot -e "SHOW DATABASES"

      - name: Checkout Redmine
        uses: actions/checkout@v4
        with:
          repository: redmine/redmine
          ref: ${{ matrix.redmine }}
          path: redmine

      - name: Checkout gemavatar
        uses: actions/checkout@v4
        with:
          repository: Boy132/redmine_gemavatar
          path: redmine/plugins/redmine_gemavatar

      - name: Update package archives
        run: sudo apt-get update --yes --quiet

      - name: Install package dependencies
        run: >
          sudo apt-get install --yes --quiet
          build-essential
          cmake
          libicu-dev
          libpq-dev
          libmysqlclient-dev

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: Prepare Redmine source
        working-directory: redmine/config
        run: |
          cp database.yml.example database.yml
          cp configuration.yml.example configuration.yml
          cp additional_environment.rb.example additional_environment.rb

      - name: Adjust database config
        working-directory: redmine/config
        run: |
          sed -i 's/localhost/127.0.0.1\n  port: ${{ job.services.mysql.ports[3306] }}/g' database.yml

      - name: Install Ruby dependencies
        working-directory: redmine
        run: |
          bundle config set --local without 'development'
          bundle install --jobs=4 --retry=3

      - name: Run Redmine rake tasks
        env:
          RAILS_ENV: test
          MYSQL_PORT: ${{ job.services.mysql.ports[3306] }}
        working-directory: redmine
        run: |
          bundle exec rake generate_secret_token
          bundle exec rake db:create db:migrate redmine:plugins:migrate

      - name: Enable Gravatar via database
        env:
          RAILS_ENV: test
          MYSQL_PORT: ${{ job.services.mysql.ports[3306] }}
        working-directory: redmine
        run: mysql -u root redminedb -e "UPDATE settings SET value = 1 WHERE name = 'gravatar_enabled';";

      - name: Run tests
        env:
          RAILS_ENV: test
          MYSQL_PORT: ${{ job.services.mysql.ports[3306] }}
        working-directory: redmine
        run: bundle exec rake redmine:plugins:test NAME=redmine_gemavatar RUBYOPT="-W0"

      - name: Run uninstall test
        env:
          RAILS_ENV: test
          MYSQL_PORT: ${{ job.services.mysql.ports[3306] }}
        working-directory: redmine
        run: bundle exec rake redmine:plugins:migrate NAME=redmine_gemavatar VERSION=0
